DROP TABLE IF EXISTS "package_name_provides";
CREATE TABLE "package_name_provides" ("id" INTEGER PRIMARY KEY  NOT NULL ,"name" CHAR,"provides" INTEGER,"package" INTEGER);
INSERT INTO "package_name_provides" VALUES(1,'d',0,1);
INSERT INTO "package_name_provides" VALUES(2,'e',0,1);
INSERT INTO "package_name_provides" VALUES(3,'f',0,1);
INSERT INTO "package_name_provides" VALUES(4,'g',1,2);
INSERT INTO "package_name_provides" VALUES(5,'h',1,2);
INSERT INTO "package_name_provides" VALUES(6,'i',0,2);
INSERT INTO "package_name_provides" VALUES(7,'j',1,3);
INSERT INTO "package_name_provides" VALUES(8,'k',0,3);
INSERT INTO "package_name_provides" VALUES(9,'l',1,4);
